apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTemplate
metadata:
  name: alaudaBuildImageAndDeployService
  annotations:
    alauda.io/displayName.zh-CN: 构建并更新服务
    alauda.io/displayName.en: Build image and update service
    alauda.io/description.zh-CN: 克隆代码并构建镜像然后使用该镜像更新特定的服务
    alauda.io/description.en: Clone code, build docker image and update a service
    alauda.io/readme.zh-CN: 克隆代码并构建镜像然后使用该镜像更新特定的服务
    alauda.io/readme.en: Clone code, build docker image and update a service
    alauda.io/version: v0.1
    alauda.io/style.icon: buildUpdateService
  labels:
    category: CICD
spec:
  engine: graph
  withSCM: true
  agent:
    label: docker
  options:
    timeout: 5400
  stages:
    - name: Clone
      tasks:
        - name: Clone
          type: public/clone
    - name: BuildImage
      tasks:
        - name: BuildImage
          type: public/alaudaBuildImage
          options:
            timeout: 3600
    - name: DeployService
      tasks:
        - name: DeployService
          type: public/alaudaDeployService
          options:
            timeout: 3600
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
  arguments:
    - displayName:
        zh-CN: "基本信息"
        en: "Basic Info"
      items:
        - name: "contextDir"
          schema:
            type: string
          binding:
            - BuildImage.args.contextDir
          display:
            type: string
            name:
              zh-CN: "构建路径"
              en: "Build context"
            description:
              zh-CN: 构建命令的执行目录
              en: Path of ci command executing
          required: true
          default: ./
    - displayName:
        zh-CN: "配置持续集成"
        en: "CI Configuration"
      items:
        - name: "ciEnabled"
          schema:
            type: boolean
          binding:
            - BuildImage.args.ciEnabled
          display:
            type: boolean
            name:
              zh-CN: "开启持续集成"
              en: "CIEnabled"
            description:
              zh-CN: 是否开启持续集成
              en: CI enabled
          required: true
          default: true
        - name: "useYaml"
          schema:
            type: boolean
          binding:
            - BuildImage.args.useYaml
          display:
            type: boolean
            name:
              zh-CN: "使用 YAML 构建的镜像"
              en: "Use YAML for CI container"
            description:
              zh-CN: 若使用自定义YAML镜像，则会使用您在代码仓库的alaudaci.yml中指定的镜像作为持续集成的运行环境。
              en: If enabled will use the alaudaci.yml file in the code repository to start a CI container.
          required: true
          default: true
          relation:
            - action: show
              when:
                name: ciEnabled
                value: true
        - name: ciImageRegistryCredentialsId
          schema:
            type: string
          binding:
            - BuildImage.args.ciImageRegistryCredentialsId
          display:
            type: alauda.io/jenkinscredentials
            related: jenkins_integration_id
            name:
              zh-CN: "CI镜像：镜像中心凭据"
              en: "CI image: Registry credentials"
            description:
              zh-CN: 用来执行构建的镜像的Registry凭据（用户名密码）
              en: Credential of ci image registry
          required: false
          relation:
            - action: show
              when:
                name: ciEnabled
                value: true
        - name: "ciYamlFile"
          schema:
            type: string
          binding:
            - BuildImage.args.ciYamlFile
          display:
            type: string
            name:
              zh-CN: "alaudaci.yml 文件路径"
              en: "alaudaci.yml's path"
            description:
              zh-CN: alaudaci.yml 文件路径
              en: Path of ci alaudaci.yml
          required: true
          default: ./alaudaci.yml
          relation:
            - action: show
              when:
                all:
                  - name: ciEnabled
                    value: true
                  - name: useYaml
                    value: true
          validation:
            pattern: .*\.yml$
        - name: "ciImage"
          schema:
            type: alauda.io/imagerepositorymix
          binding:
            - BuildImage.args.ciImage
          display:
            type: alauda.io/imagerepositorymix
            name:
              zh-CN: "CI镜像"
              en: "CI image"
            description:
              zh-CN: 用来执行构建的镜像
              en: Image to execute comand
          required: true
          relation:
            - action: show
              when:
                all:
                  - name: ciEnabled
                    value: true
                  - name: useYaml
                    value: false
        - name: "ciImageTag"
          schema:
            type: string
          binding:
            - BuildImage.args.ciImageTag
          display:
            type: alauda.io/imagetag
            related: ciImage
            name:
              zh-CN: "CI镜像Tag"
              en: "CI image tag"
            description:
              zh-CN: 用来执行构建的镜像的TAG
              en: Tag of image to execute comand
          required: true
          relation:
            - action: show
              when:
                all:
                  - name: ciEnabled
                    value: true
                  - name: useYaml
                    value: false
        - name: "ciCommands"
          schema:
            type: string
          binding:
            - BuildImage.args.ciCommands
          display:
            type: shellscripts
            name:
              zh-CN: "自定义命令"
              en: "CI commands"
            description:
              zh-CN: 执行构建过程中的自定义命令
              en: ci commands
          required: true
          relation:
            - action: show
              when:
                all:
                  - name: ciEnabled
                    value: true
                  - name: useYaml
                    value: false
    - displayName:
        zh-CN: 配置镜像仓库 
        en: Image Repository Configuration
      items:
        - name: "buildImageEnabled"
          schema:
            type: boolean
          binding:
            - BuildImage.args.buildImageEnabled
          display:
            type: boolean
            name:
              zh-CN: "生成镜像"
              en: "Build Image"
            description:
              zh-CN: 是否生成镜像
              en: Build Image
          required: true
          default: false
        - name: "dockerfilePath"
          schema:
            type: string
          binding:
            - BuildImage.args.dockerfilePath
          display:
            type: string
            name:
              zh-CN: "Dockerfile路径"
              en: "Dockerfile's path"
            description:
              zh-CN: Dockerfile的路径，不包含名称，例如当前目录./
              en: Path of Dockerfile, eg ./
          required: true
          default: ./
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
        - name: "image"
          schema:
            type: alauda.io/imagerepositorymix
          binding:
            - BuildImage.args.image
            - DeployService.args.image
          display:
            type: alauda.io/imagerepositorymix
            name:
              zh-CN: "镜像仓库"
              en: "Image repository"
            description:
              zh-CN: "构建生成的镜像"
              en: "Image repository to store the built image"
          required: true
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
        - name: "imageTag"
          schema:
            type: string
          binding:
            - BuildImage.args.imageTag
          display:
            type: string
            name:
              zh-CN: "镜像版本"
              en: "Customized image tag"
            description:
              zh-CN: "镜像版本, 例如 latest"
              en: "Customized image tag"
          default: "latest"
          required: true
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
        - name: imageExtraTag
          schema:
            type: string
          binding:
            - BuildImage.args.imageExtraTag
            - DeployService.args.imageTag
          display:
            type: string
            name:
              zh-CN: "附加版本"
              en: "Auto generated tag"
            description:
              zh-CN: "附加镜像版本, 例如 代码提交版本号"
              en: "extra image tag, eg. commitid"
          required: true
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
        - name: imageRegistryCredentialsId
          schema:
            type: string
          binding:
            - BuildImage.args.imageRegistryCredentialsId
          display:
            type: alauda.io/jenkinscredentials
            related: jenkins_integration_id
            name:
              zh-CN: "镜像中心凭据"
              en: "Registry credentials"
            description:
              zh-CN: "构建的目标镜像所在镜像中心的登录凭据"
              en: "Credentials of target registry"
          required: false
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
        - name: "useImageCache"
          schema:
            type: boolean
          binding:
            - BuildImage.args.useImageCache
          display:
            type: boolean
            name:
              zh-CN: "开启镜像缓存"
              en: "Use image cache"
            description:
              zh-CN: "开启镜像缓存"
              en: "Use image cache"
          default: true
          required: true
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
    - displayName:
        zh-CN: 更新服务 
        en: Deploy Service
      items:
        - name: containerInfo
          schema:
            type: alauda.io/newk8scontainermix
          binding:
            - DeployService.args.containerInfo
          display:
            type: alauda.io/newk8scontainermix
            name:
              zh-CN: "容器"
              en: "Container"
            description:
              zh-CN: |
                即将被更新的服务的容器,这里包含了一下字段
                1. 集群名称，表示即将更新的服务容器所在的集群
                2. 命名空间，表示即将更新的服务容器所在的集群的名空间
                3. 服务名称，表示即将更新的服务容器所在的集群的服务名称
                4. 容器名称，表示即将更新的服务容器的名称
              en: |
                The containers in the service which will be updated contain the following fields
                1.  The cluster name in which the service will be updated
                2.  The namespace in which the service will be updated
                3.  The service name which will be updated
                4.  The container name in the service which will be updated
          required: true
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
        - name: command
          schema:
            type: string
          binding:
            - DeployService.args.command
          display:
            type: string
            name:
              zh-CN: "接入点"
              en: "Entrypoint"
            description:
              zh-CN: "容器启动时执行的接入点，如果不指定，则使用原有服务接入点"
              en: "Entrypoint of container, , using original service command if it is empty"
          required: false
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
        - name: args
          schema:
            type: string
          binding:
            - DeployService.args.args
          display:
            type: string
            name:
              zh-CN: "执行命令"
              en: "Run Command"
            description:
              zh-CN: "容器启动时执行的命令，如果不指定，则使用原有服务命令"
              en: "Command of container, using original service command if it is empty"
          required: false
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
        - name: env
          schema:
            type: alauda.io/k8senv
          binding:
            - DeployService.args.env
          display:
            type: alauda.io/k8senv
            name:
              zh-CN: "环境变量"
              en: "Environment variables"
            description:
              zh-CN: "环境变量"
              en: "Environment variables"
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true
        - name: timeout
          schema:
            type: int
          binding:
            - DeployService.args.timeout
          display:
            type: int
            name:
              zh-CN: "超时时间（秒）"
              en: "Timeout (s)"
            description:
              zh-CN: "超时时间（秒）"
              en: "Timeout (s)"
          required: true
          relation:
            - action: show
              when:
                name: buildImageEnabled
                value: true



